spring:
  application:
    name: api-gateway
  cloud:
    kubernetes:
      reload:
        enabled: true
        url-expression: "uri+'/'"
      discovery:
        enabled: true
  port: 8089
ribbon:
  http:
    client:
      enabled: true
logging:
  logstash:
    host: localhost:9500
    enabled: false