spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    kubernetes:
      reload:
        enabled: false
        url-expression: "uri+'/'"
      discovery:
        enabled: false
#        server-url: "https://82.73.212.90:16443"
        locator:
          enabled: false
          url-expression: "http://'+serviceId+':'+getPort()"
          lower-case-service-id: true
  port: 8089
ribbon:
  http:
    client:
      enabled: true
logging:
  logstash:
    host: localhost:9500
    enabled: false
