spring:
  application:
    name: api-gateway
  cloud:
    kubernetes:
      reload:
        enabled: true
        url-expression: "'http://'+serviceId+':'+getPort()"
      discovery:
        enabled: true
  port: 8089

logging:
  logstash:
    host: localhost:9500
    enabled: false