spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8089

eureka:
  client:
    register-with-eureka: false
    fetch-registry: true

logging:
  logstash:
    host: localhost:9500
    enabled: true