spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    kubernetes:
      reload:
        enabled: true
        url-expression: "uri+'/'"
      discovery:
        locator:
          enabled: true
          url-expression: "http://'+serviceId+':'+getPort()"
          lower-case-service-id: true
        enabled: true
  port: 8089
#ribbon:
#  http:
#    client:
#      enabled: true
logging:
  logstash:
    host: localhost:9500
    enabled: false
